STXXL: stxxl::potentially_parallel Namespace Reference
stxxl::potentially_parallel Namespace Reference
this namespace provides parallel or sequential algorithms depending on the compilation settings. it should be used by all components, where parallelism is optional.
Functions
template<typename RandomAccessIteratorPairIterator , typename RandomAccessIterator3 , typename DiffType , typename Comparator >
RandomAccessIterator3 multiway_merge (RandomAccessIteratorPairIterator seqs_begin, RandomAccessIteratorPairIterator seqs_end, RandomAccessIterator3 target, DiffType length, Comparator comp)
Multi-way merging dispatcher.
template<typename RandomAccessIteratorPairIterator , typename RandomAccessIterator3 , typename DiffType , typename Comparator >
RandomAccessIterator3 multiway_merge_sentinels (RandomAccessIteratorPairIterator seqs_begin, RandomAccessIteratorPairIterator seqs_end, RandomAccessIterator3 target, DiffType length, Comparator comp)
Multi-way merging front-end.
template<typename RandomAccessIteratorPairIterator , typename RandomAccessIterator3 , typename DiffType , typename Comparator >
RandomAccessIterator3 multiway_merge_stable (RandomAccessIteratorPairIterator seqs_begin, RandomAccessIteratorPairIterator seqs_end, RandomAccessIterator3 target, DiffType length, Comparator comp)
Multi-way merging dispatcher.
template<typename RandomAccessIteratorPairIterator , typename RandomAccessIterator3 , typename DiffType , typename Comparator >
RandomAccessIterator3 multiway_merge_stable_sentinels (RandomAccessIteratorPairIterator seqs_begin, RandomAccessIteratorPairIterator seqs_end, RandomAccessIterator3 target, DiffType length, Comparator comp)
Multi-way merging front-end.
Detailed Description
this namespace provides parallel or sequential algorithms depending on the compilation settings. it should be used by all components, where parallelism is optional.
Function Documentation
template<typename RandomAccessIteratorPairIterator , typename RandomAccessIterator3 , typename DiffType , typename Comparator > RandomAccessIterator3 stxxl::potentially_parallel::multiway_merge (RandomAccessIteratorPairIterator seqs_begin, RandomAccessIteratorPairIterator seqs_end, RandomAccessIterator3 target, DiffType length, Comparator comp)
Multi-way merging dispatcher.
Parameters
seqs_begin Begin iterator of iterator pair input sequence.
seqs_end End iterator of iterator pair input sequence.
target Begin iterator out output sequence.
comp Comparator.
length Maximum length to merge.
Returns
End iterator of output sequence.
Definition at line 144 of file parallel.h.
Referenced by stxxl::parallel_priority_queue< ValueType, CompareType, AllocStrategy, BlockSize, DefaultMemSize, MaxItems >::add_as_internal_array(), stxxl::parallel_priority_queue< ValueType, CompareType, AllocStrategy, BlockSize, DefaultMemSize, MaxItems >::bulk_pop_limit(), stxxl::stream::basic_runs_merger< typename runs_creator_type::sorted_runs_type, cmp_type, alloc_strategy_type >::fill_buffer_block(), stxxl::parallel_priority_queue< ValueType, CompareType, AllocStrategy, BlockSize, DefaultMemSize, MaxItems >::flush_insertion_heaps(), stxxl::parallel_priority_queue< ValueType, CompareType, AllocStrategy, BlockSize, DefaultMemSize, MaxItems >::flush_internal_arrays(), stxxl::parallel_priority_queue< ValueType, CompareType, AllocStrategy, BlockSize, DefaultMemSize, MaxItems >::merge_external_arrays(), stxxl::sort_local::merge_runs(), and stxxl::parallel_priority_queue< ValueType, CompareType, AllocStrategy, BlockSize, DefaultMemSize, MaxItems >::refill_extract_buffer().
template<typename RandomAccessIteratorPairIterator , typename RandomAccessIterator3 , typename DiffType , typename Comparator > RandomAccessIterator3 stxxl::potentially_parallel::multiway_merge_sentinels (RandomAccessIteratorPairIterator seqs_begin, RandomAccessIteratorPairIterator seqs_end, RandomAccessIterator3 target, DiffType length, Comparator comp)
Multi-way merging front-end.
Parameters
seqs_begin Begin iterator of iterator pair input sequence.
seqs_end End iterator of iterator pair input sequence.
target Begin iterator out output sequence.
comp Comparator.
length Maximum length to merge.
Returns
End iterator of output sequence.
Precondition
For each i, seqs_begin[i].second must be the end marker of the sequence, but also reference the one more sentinel element.
Definition at line 195 of file parallel.h.
Referenced by stxxl::priority_queue_local::loser_tree< ValueType, CompareType, MaxArity >::multi_merge(), and stxxl::priority_queue< ConfigType >::refill_delete_buffer().
template<typename RandomAccessIteratorPairIterator , typename RandomAccessIterator3 , typename DiffType , typename Comparator > RandomAccessIterator3 stxxl::potentially_parallel::multiway_merge_stable (RandomAccessIteratorPairIterator seqs_begin, RandomAccessIteratorPairIterator seqs_end, RandomAccessIterator3 target, DiffType length, Comparator comp)
Multi-way merging dispatcher.
Parameters
seqs_begin Begin iterator of iterator pair input sequence.
seqs_end End iterator of iterator pair input sequence.
target Begin iterator out output sequence.
comp Comparator.
length Maximum length to merge.
Returns
End iterator of output sequence.
Definition at line 169 of file parallel.h.
template<typename RandomAccessIteratorPairIterator , typename RandomAccessIterator3 , typename DiffType , typename Comparator > RandomAccessIterator3 stxxl::potentially_parallel::multiway_merge_stable_sentinels (RandomAccessIteratorPairIterator seqs_begin, RandomAccessIteratorPairIterator seqs_end, RandomAccessIterator3 target, DiffType length, Comparator comp)
Multi-way merging front-end.
Parameters
seqs_begin Begin iterator of iterator pair input sequence.
seqs_end End iterator of iterator pair input sequence.
target Begin iterator out output sequence.
comp Comparator.
length Maximum length to merge.
Returns
End iterator of output sequence.
Precondition
For each i, seqs_begin[i].second must be the end marker of the sequence, but also reference the one more sentinel element.
Definition at line 221 of file parallel.h.