Stxxl: disk_queued_file Class Reference
disk_queued_file Class Reference
File implementations
Implementation of some file methods based on serving_request.
#include <disk_queued_file.h>
Public Member Functions
disk_queued_file (int queue_id, int allocator_id)
request_ptr aread (void *buffer, offset_type pos, size_type bytes, const completion_handler &on_cmpl)
Schedules an asynchronous read request to the file.
request_ptr awrite (void *buffer, offset_type pos, size_type bytes, const completion_handler &on_cmpl)
Schedules an asynchronous write request to the file.
virtual int get_queue_id () const
Returns the identifier of the file's queue.
virtual int get_allocator_id () const
Returns the file's allocator.
Public Member Functions inherited from file
virtual void serve (const request *req)=0 throw (io_error)
void add_request_ref ()
void delete_request_ref ()
int get_request_nref ()
virtual void set_size (offset_type newsize)=0
Changes the size of the file.
virtual offset_type size ()=0
Returns size of the file.
virtual int get_physical_device_id () const
virtual void lock ()=0
Locks file for reading and writing (acquires a lock in the file system)
virtual void discard (offset_type offset, offset_type size)
Discard a region of the file (mark it unused) some specialized file types may need to know freed regions.
virtual void export_files (offset_type offset, offset_type length, std::string prefix)
virtual void remove ()
virtual const char * io_type () const
Identifies the type of I/O implementation.
Additional Inherited Members
Public Types inherited from file
enum open_mode {
RDONLY = 1, WRONLY = 2, RDWR = 4, CREAT = 8,
DIRECT = 16, TRUNC = 32, SYNC = 64, NO_LOCK = 128
}
Definition of acceptable file open modes.
typedef request::offset_type offset_type
typedef request::size_type size_type
Static Public Attributes inherited from file
static const int DEFAULT_QUEUE = -1
static const int NO_QUEUE = -2
static const int NO_ALLOCATOR = -1
Protected Member Functions inherited from file
file ()
Initializes file object.
Detailed Description
Implementation of some file methods based on serving_request.
Member Function Documentation
__STXXL_BEGIN_NAMESPACE request_ptr disk_queued_file::aread (void * buffer, offset_type pos, size_type bytes, const completion_handler & on_cmpl) virtual
Schedules an asynchronous read request to the file.
Parameters
buffer pointer to memory buffer to read into
pos file position to start read from
bytes number of bytes to transfer
on_cmpl I/O completion handler
Returns
request_ptr request object, which can be used to track the status of the operation
Implements file.
References get_queue_id().
request_ptr disk_queued_file::awrite (void * buffer, offset_type pos, size_type bytes, const completion_handler & on_cmpl) virtual
Schedules an asynchronous write request to the file.
Parameters
buffer pointer to memory buffer to write from
pos starting file position to write
bytes number of bytes to transfer
on_cmpl I/O completion handler
Returns
request_ptr request object, which can be used to track the status of the operation
Implements file.
References get_queue_id().
virtual int disk_queued_file::get_allocator_id () const inline virtual
Returns the file's allocator.
Returns
allocator number
Implements file.
virtual int disk_queued_file::get_queue_id () const inline virtual
Returns the identifier of the file's queue.
Remarks
Files allocated on the same physical device usually share the same queue
Returns
queue number
Implements file.
Referenced by aread(), and awrite().
The documentation for this class was generated from the following files:
disk_queued_file.h
disk_queued_file.cpp