Stxxl: malloc_stats Class Reference
malloc_stats Class Reference
Access to some useful malloc statistics.
#include <malloc.h>
Public Types
typedef int return_type
Public Member Functions
return_type from_system_nmmap () const
Returns number of bytes allocated from system not including mmapped regions.
return_type free_chunks () const
Returns number of free chunks.
return_type used () const
Number of bytes allocated and in use.
return_type not_used () const
Number of bytes allocated but not in use.
return_type releasable () const
Top-most, releasable (via malloc_trim) space (bytes)
return_type max_allocated () const
Maximum total allocated space (bytes) (always 0 ?)
return_type fastbin_blocks () const
Number of fastbin blocks.
return_type fastbin_free () const
Space available in freed fastbin blocks (bytes)
return_type from_system_mmap () const
Returns number of bytes allocated from system using mmap.
return_type mmap_chunks () const
Number of chunks allocated via mmap()
return_type from_system_total () const
Returns total number of bytes allocated from system including mmapped regions.
Detailed Description
Access to some useful malloc statistics.
malloc is default C++ allocator
Member Function Documentation
return_type malloc_stats::fastbin_blocks () const inline
Number of fastbin blocks.
return_type malloc_stats::fastbin_free () const inline
Space available in freed fastbin blocks (bytes)
return_type malloc_stats::free_chunks () const inline
Returns number of free chunks.
return_type malloc_stats::from_system_mmap () const inline
Returns number of bytes allocated from system using mmap.
Referenced by from_system_total().
return_type malloc_stats::from_system_nmmap () const inline
Returns number of bytes allocated from system not including mmapped regions.
Referenced by from_system_total().
return_type malloc_stats::from_system_total () const inline
Returns total number of bytes allocated from system including mmapped regions.
References from_system_mmap(), and from_system_nmmap().
return_type malloc_stats::max_allocated () const inline
Maximum total allocated space (bytes) (always 0 ?)
return_type malloc_stats::mmap_chunks () const inline
Number of chunks allocated via mmap()
return_type malloc_stats::not_used () const inline
Number of bytes allocated but not in use.
return_type malloc_stats::releasable () const inline
Top-most, releasable (via malloc_trim) space (bytes)
return_type malloc_stats::used () const inline
Number of bytes allocated and in use.
The documentation for this class was generated from the following file:
malloc.h