Stxxl: stream::transform< Operation_, Input1_, Input2_, Input3_, Input4_, Input5_, Input6_ > Class Template Reference
stream::transform< Operation_, Input1_, Input2_, Input3_, Input4_, Input5_, Input6_ > Class Template Reference
Stream package
Processes (up to) 6 input streams using given operation functor.
#include <stream.h>
Public Types
typedef Operation_::value_type value_type
Standard stream typedef.
Public Member Functions
transform (Operation_ &o, Input1_ &i1_, Input2_ &i2_, Input3_ &i3_, Input4_ &i4_, Input5_ &i5_, Input5_ &i6_)
Construction.
const value_type & operator* () const
Standard stream method.
const value_type * operator-> () const
transform & operator++ ()
Standard stream method.
bool empty () const
Standard stream method.
Detailed Description
template<class Operation_, class Input1_, class Input2_ = Stopper, class Input3_ = Stopper, class Input4_ = Stopper, class Input5_ = Stopper, class Input6_ = Stopper>
class stream::transform< Operation_, Input1_, Input2_, Input3_, Input4_, Input5_, Input6_ >
Processes (up to) 6 input streams using given operation functor.
Template Parameters
Operation_ type of the operation (type of an adaptable functor that takes 6 parameters)
Input1_ type of the 1st input
Input2_ type of the 2nd input
Input3_ type of the 3rd input
Input4_ type of the 4th input
Input5_ type of the 5th input
Input6_ type of the 6th input
Member Typedef Documentation
template<class Operation_ , class Input1_ , class Input2_ = Stopper, class Input3_ = Stopper, class Input4_ = Stopper, class Input5_ = Stopper, class Input6_ = Stopper> typedef Operation_::value_type stream::transform< Operation_, Input1_, Input2_, Input3_, Input4_, Input5_, Input6_ >::value_type
Standard stream typedef.
Constructor & Destructor Documentation
template<class Operation_ , class Input1_ , class Input2_ = Stopper, class Input3_ = Stopper, class Input4_ = Stopper, class Input5_ = Stopper, class Input6_ = Stopper> stream::transform< Operation_, Input1_, Input2_, Input3_, Input4_, Input5_, Input6_ >::transform (Operation_ & o, Input1_ & i1_, Input2_ & i2_, Input3_ & i3_, Input4_ & i4_, Input5_ & i5_, Input5_ & i6_) inline
Construction.
References stream::transform< Operation_, Input1_, Input2_, Input3_, Input4_, Input5_, Input6_ >::empty().
Member Function Documentation
template<class Operation_ , class Input1_ , class Input2_ = Stopper, class Input3_ = Stopper, class Input4_ = Stopper, class Input5_ = Stopper, class Input6_ = Stopper> bool stream::transform< Operation_, Input1_, Input2_, Input3_, Input4_, Input5_, Input6_ >::empty () const inline
Standard stream method.
Referenced by stream::transform< Operation_, Input1_, Input2_, Input3_, Input4_, Input5_, Input6_ >::operator++(), stream::transform< Operation_, Input1_, Stopper, Stopper, Stopper, Stopper, Stopper >::operator++(), stream::transform< Operation_, Input1_, Input2_, Stopper, Stopper, Stopper, Stopper >::operator++(), stream::transform< Operation_, Input1_, Input2_, Input3_, Stopper, Stopper, Stopper >::operator++(), stream::transform< Operation_, Input1_, Input2_, Input3_, Input4_, Stopper, Stopper >::operator++(), stream::transform< Operation_, Input1_, Input2_, Input3_, Input4_, Input5_, Stopper >::operator++(), stream::transform< Operation_, Input1_, Input2_, Input3_, Input4_, Input5_, Input6_ >::transform(), stream::transform< Operation_, Input1_, Stopper, Stopper, Stopper, Stopper, Stopper >::transform(), stream::transform< Operation_, Input1_, Input2_, Stopper, Stopper, Stopper, Stopper >::transform(), stream::transform< Operation_, Input1_, Input2_, Input3_, Stopper, Stopper, Stopper >::transform(), stream::transform< Operation_, Input1_, Input2_, Input3_, Input4_, Stopper, Stopper >::transform(), and stream::transform< Operation_, Input1_, Input2_, Input3_, Input4_, Input5_, Stopper >::transform().
template<class Operation_ , class Input1_ , class Input2_ = Stopper, class Input3_ = Stopper, class Input4_ = Stopper, class Input5_ = Stopper, class Input6_ = Stopper> const value_type& stream::transform< Operation_, Input1_, Input2_, Input3_, Input4_, Input5_, Input6_ >::operator* () const inline
Standard stream method.
template<class Operation_ , class Input1_ , class Input2_ = Stopper, class Input3_ = Stopper, class Input4_ = Stopper, class Input5_ = Stopper, class Input6_ = Stopper> transform& stream::transform< Operation_, Input1_, Input2_, Input3_, Input4_, Input5_, Input6_ >::operator++ () inline
Standard stream method.
References stream::transform< Operation_, Input1_, Input2_, Input3_, Input4_, Input5_, Input6_ >::empty().
The documentation for this class was generated from the following file:
stream.h