Stxxl: Block management layer
Block management layer
Modules
Allocation functors
Block scheduling sublayer
Classes
struct BID< SIZE >
Block identifier class.
class config
Access point to disks properties.
class block_manager
Block manager class.
Macros
#define STXXL_ADAPTOR_ARITHMETICS(pos)
#define BLOCK_ADAPTOR_OPERATORS(two_to_one_dim_array_adaptor_base)
#define STXXL_DEFAULT_BLOCK_SIZE(type) (2 * 1024 * 1024)
Functions
template<typename BlockType >
element_iterator_traits
< BlockType >
::element_iterator make_element_iterator (BlockType *blocks, unsigned_type offset)
template<class BIDType , class DiskAssignFunctor , class OutputIterator >
void block_manager::new_blocks_int (const unsigned_type nblocks, const DiskAssignFunctor &functor, unsigned_type offset, OutputIterator out)
template<unsigned BLK_SIZE>
void block_manager::delete_block (const BID< BLK_SIZE > &bid)
Deallocates a block.
template<class BIDIteratorClass >
void block_manager::delete_blocks (const BIDIteratorClass &bidbegin, const BIDIteratorClass &bidend)
Deallocates blocks.
Detailed Description
Group of classes which help controlling external memory space, managing disks, and allocating and deallocating blocks of external storage
Function Documentation
template<unsigned BLK_SIZE> void block_manager::delete_block (const BID< BLK_SIZE > & bid)
Deallocates a block.
Parameters
bid block identifier
References file::discard(), file::get_allocator_id(), BID< SIZE >::offset, BID< SIZE >::size, and BID< SIZE >::storage.
Referenced by block_manager::delete_blocks(), ksort(), queue< ValTp, BlkSz, AllocStr, SzTp >::pop(), and sort().
template<class BIDIteratorClass > void block_manager::delete_blocks (const BIDIteratorClass & bidbegin, const BIDIteratorClass & bidend)
Deallocates blocks.
Deallocates blocks in the range [ bidbegin, bidend)
Parameters
bidbegin iterator object of bid_iterator concept
bidend iterator object of bid_iterator concept
References block_manager::delete_block().
Referenced by stream::sorted_runs< trigger_entry_type >::deallocate_blocks().